### ISSUE TITLE
Sizes unreadable over certain backgrounds

### ISSUE THREAD

**Issue by ghost** [tsl143/jsDemos#1]
I've got a page with the color #950306 as background, over that, the 2 sizes are shown in white text over white cell's background, unreadable.

**Comment by b3wii** [comment]
Yes unreadable especially on opened images. Please fix this
![unbenannt](https://user-images.githubusercontent.com/3820367/31546978-e2729916-b025-11e7-9b86-34a73bc1175b.png)

**Comment by worldsdream** [comment]
It would be great if we could change the colors and opacity of both the ruler and background.

**Comment by tsl143** [comment]
Thanks for all inputs, This has been fixed in version 2.1.0 and updated in addons.mozilla.org and chrome store.
