### ISSUE TITLE
How to make this work on FF 68?

### ISSUE THREAD

**Issue by ghost** [tsl143/jsDemos#11]
On MacOS, CTRL + SHIFT + F does not work. I'm reading the notes, and I don't understand what this means: "Due to webextensions constraint, it doesn't work on addons.mozilla.org".

Is it related? Thanks!

**Comment by arandorion** [comment]
I have the same problem. I'm using Firefox 69.0.2 on macOS 10.14.5.  When I press ctrl + shift + f, it simply performs the usual full-screen behavior where tabs and the address bar are still visible.

I too saw the note:
> Due to webextensions constraint, it doesn't work on addons.mozilla.org.

Does that means it it doesn't put that site (addons.mozilla.org) in full-screen or that the add-on itself downloaded from addon.mozilla.org does not work.

Is the Fullscreen Plus add-on supposed to work with Firefox 68+ on macOS?

Thanks

**Comment by tsl143** [comment]
I believe its a bit late to reply :( ,
but anyways this works of FF70 on macOS as expected `ctrl + shift + f` opens full screen without urlbar

**Comment by ghost** [comment]
Thanks :) its working now. I don't know what changed - but it's consistent.

**Comment by tsl143** [comment]
Perfect, then closing this issue :)
