### ISSUE TITLE
Firefox Fullscreen Plugin

### ISSUE THREAD

**Issue by voidCAPITALism** [tsl143/jsDemos#7]
event.stopPropagation() prevents any other keylistener to get key presses.

So:

const allowFullScreen = event => {
	event.preventDefault();
  	event = event || window.event;
    if(event.ctrlKey && event.keyCode==70 && event.shiftKey) {
        document.documentElement.mozRequestFullScreen();
    }
}

document.addEventListener('keyup', allowFullScreen)

**Comment by tsl143** [comment]
Updated in version 2.0
